version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mariadb:
      image: mariadb
      restart: unless-stopped
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      restart: unless-stopped
      ports:
      - "8383:8080"
      - "8443:8443"
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: H7m1s634
        JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      depends_on:
        - mariadb